global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@claims.com'
  smtp_auth_username: 'alerts@claims.com'
  smtp_auth_password: 'your-email-password'

route:
  group_by: ['alertname', 'category']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
    
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 2h
    
    - match:
        category: business
      receiver: 'business-alerts'
      repeat_interval: 1h
    
    - match:
        category: ml_performance
      receiver: 'ml-alerts'
      repeat_interval: 30m
    
    - match:
        category: security
      receiver: 'security-alerts'
      group_wait: 0s
      repeat_interval: 15m

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://notification-service:8000/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alertmanager'
            password: 'webhook-secret'

  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@claims.com'
        subject: '🚨 CRITICAL: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Category: {{ .Labels.category }}
          Service: {{ .Labels.job }}
          Instance: {{ .Labels.instance }}
          
          Labels:
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}
    
    webhook_configs:
      - url: 'http://notification-service:8000/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alertmanager'
            password: 'webhook-secret'

  - name: 'warning-alerts'
    email_configs:
      - to: 'team@claims.com'
        subject: '⚠️ WARNING: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Category: {{ .Labels.category }}
          Service: {{ .Labels.job }}
          
          View in Grafana: http://grafana:3003/d/claims-overview
          {{ end }}

  - name: 'business-alerts'
    email_configs:
      - to: 'business@claims.com'
        subject: '📊 Business Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          Business Impact Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Impact: {{ .Labels.category }}
          
          Please review the business metrics dashboard:
          http://grafana:3003/d/business-metrics
          {{ end }}

  - name: 'ml-alerts'
    email_configs:
      - to: 'ml-team@claims.com'
        subject: '🤖 ML Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          Machine Learning Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Model Impact: {{ .Labels.category }}
          
          Check ML monitoring dashboard:
          http://grafana:3003/d/ml-monitoring
          MLOps Service: http://mlops-service:8000/docs
          {{ end }}

  - name: 'security-alerts'
    email_configs:
      - to: 'security@claims.com'
        subject: '🔒 SECURITY ALERT: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          SECURITY INCIDENT DETECTED
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Source: {{ .Labels.instance }}
          
          IMMEDIATE ACTION REQUIRED
          {{ end }}
    
    webhook_configs:
      - url: 'http://notification-service:8000/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alertmanager'
            password: 'webhook-secret'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'job', 'instance']

  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*'
    equal: ['job', 'instance'] 